
# Backgrounds (as png images)
image bg Hallway = "images/Backgrounds/Hallway.png" # Imported as "scene bg Hallway"
image bg Hallway Sunset = "images/Backgrounds/DormHallwaySunset.png"
image bg white = "images/Backgrounds/flashbang.png" # Imported as "scene bg white", its the thing right after the splash screen

image bg Bedroom = "images/Backgrounds/ARBEDROOM.png" # Imported as "Bedroom", it's Andee's and Reo's bedroom lol
image bg Bathroom = "images/Backgrounds/ARBATHROOM.png" # Imported as "Bathroom", it's the chiottes de leo et andee as they say in the french
image bg Bathroom steamy = "images/Backgrounds/ARBATHROOMSTEAMY.png" # Imported as "Bathroom steamy", its the same bathroom but with steam, you know for the hot shower scene
image bg Kitchen = "images/Backgrounds/ARKITCHEN.PNG" # Imported as "Kitchen", needs to be changed, ell pelo deir comehr
image bg office door = "images/backgrounds/office door.png" # imported as office door, its haddies office!
image bg haddiesoffice = "images/backgrounds/HaddiesOffice.png" #imported as haddiesoffice, someones in troubleeeeeee
image bg void = "images/backgrounds/void.png" # void.like
image bg Campus Outside = "images/Backgrounds/CampusOutside.png" #imported as Campus Outside, bitch we outsideee
image bg Livingroom = "images/Backgrounds/ARLIVINGROOM.png" #imported as ARLIVINGROOM, home sweet home
image bg Stairs = "images/Backgrounds/Stairs.png"
image Malevolent = "images/Splash/Malevolent.png"
image Team Ikigai = "images/Splash/TeamIkigai.png"
image Disclaimer = "images/Splash/Disclaimer.png"
image Warning = "images/Splash/Warning.png"
image bg CampusDoorsInside = "images/Backgrounds/insidecampusdoors.png"
image bg Classhall2 = "images/Backgrounds/Classhall2.png"
image bg Classroom Hall = "images/Backgrounds/Classroom Hall.png"
image bg back classroom = "images/Backgrounds/backclassroom.png"
image bg front classroom = "images/Backgrounds/frontclassroom.png"
image bg Library = "images/Backgrounds/Library.png"
image bg bedroom night = "images/Backgrounds/BEDROOMNIGHT.png"
image bg livingroom night = "images/Backgrounds/ARLIVINGROOMNIGHT.png"
image bg livingroom sunset = "images/Backgrounds/ARLIVINGROOMSUNSET.png"
image bg dormhallway night = "images/Backgrounds/DormHallwayNight.png"
image bg Beach = "images/Backgrounds/Beach (Day).webp"
image bg Beach Sunset = "images/Backgrounds/Beach Sunset.webp"
image bg Beach Night = "images/Backgrounds/Beach Night.webp"
image bg dormhallway sunset = "images/Backgrounds/DormHallwaySunset.png"
image bg gym = "images/Backgrounds/Campus Gym.png"
image bg myikigai = "images/Backgrounds/My Ikigai.png"
image bg dockscafe = "images/Backgrounds/DocksCafe.png"
image bg dockscafe sunset = "images/Backgrounds/Docks Cafe Sunset.jpg"
image bg DetectivesOffice = "images/Backgrounds/DetectivesOffice.png"
image bg cafeteria = "images/Backgrounds/Cafeteria.png"
image bg library shelves = "images/Backgrounds/library shelves.png"
image bg Study Corner = "images/Backgrounds/Study Corner.png"

image Reo Neutral ="images/Characters/Reo Neutral.png"
image Andreas Neutral = "images/Characters/Andreas Neutral.png"
image Ax Neutral = "images/Characters/Ax Neutral.png"
image Calvin Neutral = "images/Characters/Calvin Neutral.png"
image Dock Neutral = "images/Characters/Dock Neutral.png"
image Esha Neutral = "images/Characters/Esha Neutral.png"
image Hiro Neutral = "images/Characters/Hiro Neutral.png"
image Tony Neutral = "images/Characters/Tony Neutral.png"
image Tyson Neutral = "images/Characters/Tyson Neutral.png"
