label test:
    scene bg Hallway

    "You wake up in a dark room."
    "It’s cold."
    "Really cold."
    "Your fur’s standing on end."

    Andee "...Ugh-"
    Andee "Where... am i?"
    "You stumble to your feet."
    Andee "Hello? Is anybody here?"
    Andee "And where IS here?"
    whotf2 "Welcome."
# music: a shockwave
    Andee "G-Gah-!"
    "The voice startles you. Something feels very wrong about it, like a whisper in your neck that echoed from miles away."
    Andee "Who's there?! What's this?!"
    whotf2 "Calm yourself, young one."
    whotf2 "We are only going to run a assessment to gauge how you may respond in... certain scenarios."
    Andee "...We?"
    "A blinding light snaps on above you. Three shadowed figures stand behind a pane of glass, their faces obscured."
    "You've just noticed now that you're only wearing underwear-..."
    Andee "W-what the-... WHERE ARE MY CLOTHES?!"
    whotf2 "State your name."
    Andee "My... name?"
    "You begin to speak with hesitation."
    Andee "...It's Andee."
    "One of the figures scribbles something in what looks to be a notepad, but it's hard to tell in the darkness."
    whotf2 "Age."
    Andee "I'm 19...?"
    "They scribble something loudly again."
    whotf2 "Why did you come here?"
    Andee "Come where??"
    "You're getting a bit fed up by whatever this is."
    Andee "Look, mysterious voice or whatever, are you gonna keep being cryptic or are you gonna tell me what this is about already?"
    "Suddenly, your head pounds."
    Andee "A-ARGH-..."
    Andee "T-The last thing i remember was... Being on the flight to Hibana..."
    Andee "...Dang it, i'm gonna miss my first day."
    whotf2 "Do you trust easily?"
    Andee "I-..."
    "You stay silent for a moment, thinking of the options."
    Andee "Maybe... sometimes-...?"
    whotf2 "Would you say you forgive things easily?"
    "Yes you do. Too easily."
    Andee "...Yeah."
    whotf2 "Do you belive your friends would describe you as loyal?"
    "..."
    Andee "I'd- hope so?" # would be nice to make a tiny pause at the "id"
    "The room goes completely silent."
    whotf2 "Interesting. Very, interesting."
    whotf2 "Do you belive you deserve to be here?"
    Andee "Here? D-deserve to be where?.. Look, this is really freaking me out. Where the heck am I- what is this fo-..."
    # beeping sounds pls + music stops
    # should prob makes another file for the rest